"""Sample data for template variables.

This data is used by the /api/variables endpoint to show examples
in the template editor UI. Extracted from V1's variables.json.
"""

# Maps variable name -> dict of sport -> example value
VARIABLE_EXAMPLES: dict[str, dict[str, str]] = {
    "attendance": {
        "NBA": "20,332",
        "NFL": "65,000",
        "MLB": "41,083",
        "NHL": "19,515",
        "NCAAM": "12,707",
        "NCAAF": "107,601",
        "Soccer": "61,276",
    },
    "away_record": {
        "NBA": "6-1",
        "NFL": "5-1",
        "MLB": "41-40",
        "NHL": "5-4-0",
        "NCAAM": "1-0",
        "NCAAF": "4-1",
        "Soccer": "5-1-1",
    },
    "away_streak": {
        "NBA": "W7",
        "NFL": "W2",
        "MLB": "W1",
        "NHL": "L1",
        "NCAAM": "W1",
        "NCAAF": "W1",
        "Soccer": "W2",
    },
    "away_team": {
        "NBA": "Indiana Pacers",
        "NFL": "Green Bay Packers",
        "MLB": "Cleveland Guardians",
        "NHL": "New Jersey Devils",
        "NCAAM": "Ohio State Buckeyes",
        "NCAAF": "Ohio State Buckeyes",
        "Soccer": "Manchester City",
    },
    "away_team_abbrev": {
        "NBA": "IND",
        "NFL": "GB",
        "MLB": "CLE",
        "NHL": "NJD",
        "NCAAM": "OSU",
        "NCAAF": "OSU",
        "Soccer": "MCI",
    },
    "away_team_abbrev_lower": {
        "NBA": "ind",
        "NFL": "gb",
        "MLB": "cle",
        "NHL": "njd",
        "NCAAM": "osu",
        "NCAAF": "osu",
        "Soccer": "mci",
    },
    "away_team_college_conference": {"NCAAM": "Big Ten", "NCAAF": "Big Ten"},
    "away_team_college_conference_abbrev": {"NCAAM": "B1G", "NCAAF": "B1G"},
    "away_team_logo": {"All": "https://a.espncdn.com/i/teamlogos/..."},
    "away_team_pascal": {
        "NBA": "IndianaPacers",
        "NFL": "GreenBayPackers",
        "MLB": "ClevelandGuardians",
        "NHL": "StLouisBlues",
        "NCAAM": "OhioStateBuckeyes",
        "NCAAF": "OhioStateBuckeyes",
        "Soccer": "ManchesterCity",
    },
    "away_team_pro_conference": {
        "NBA": "Eastern Conference",
        "NFL": "National Football Conference",
        "MLB": "American League",
        "NHL": "Eastern Conference",
    },
    "away_team_pro_conference_abbrev": {"NBA": "East", "NFL": "NFC", "MLB": "AL", "NHL": "East"},
    "away_team_pro_division": {
        "NBA": "Central",
        "NFL": "NFC North",
        "MLB": "AL Central",
        "NHL": "Metropolitan Division",
        "Soccer": "English Premier League",
    },
    "away_team_rank": {"NCAAM": "#8", "NCAAF": "#3"},
    "away_team_record": {
        "NBA": "8-8",
        "NFL": "7-4",
        "MLB": "92-70",
        "NHL": "15-7-2",
        "NCAAM": "3-1",
        "NCAAF": "10-1",
        "Soccer": "7-4-3",
    },
    "away_team_score": {"NBA": "98", "NFL": "17", "MLB": "3", "NHL": "2"},
    "away_team_seed": {"NBA": "5th", "NFL": "7th", "MLB": "6th", "NHL": "8th"},
    "away_team_streak": {
        "NBA": "L3",
        "NFL": "W4",
        "MLB": "L1",
        "NHL": "W6",
        "NCAAM": "L2",
        "NCAAF": "W8",
        "Soccer": "L1",
    },
    "away_win_pct": {
        "NBA": "0.857",
        "NFL": "0.833",
        "MLB": "0.506",
        "NHL": "0.556",
        "NCAAM": "1.000",
        "NCAAF": "0.800",
        "Soccer": "0.714",
    },
    "basketball_scoring_leader_name": {"NBA": "Cade Cunningham", "NCAAM": "Tre Donaldson"},
    "basketball_scoring_leader_points": {"NBA": "28", "NCAAM": "22"},
    "broadcast_national_network": {
        "NBA": "ESPN",
        "NFL": "FOX",
        "MLB": "FOX",
        "NHL": "ESPN",
        "NCAAM": "ESPN",
        "NCAAF": "FOX",
        "Soccer": "USA Network",
    },
    "broadcast_network": {
        "NBA": "ESPN",
        "NFL": "FOX",
        "MLB": "FOX",
        "NHL": "ESPN",
        "NCAAM": "ESPN",
        "NCAAF": "FOX",
        "Soccer": "USA Network",
    },
    "broadcast_simple": {
        "NBA": "ESPN",
        "NFL": "FOX",
        "MLB": "FOX",
        "NHL": "ESPN",
        "NCAAM": "ESPN",
        "NCAAF": "FOX",
        "Soccer": "USA Network",
    },
    "college_conference": {"NCAAM": "Big Ten", "NCAAF": "Big Ten"},
    "college_conference_abbrev": {"NCAAM": "B1G", "NCAAF": "B1G"},
    "days_until": {
        "NBA": "0",
        "NFL": "3",
        "MLB": "131",
        "NHL": "5",
        "NCAAM": "51",
        "NCAAF": "5",
        "Soccer": "7",
    },
    "event_name": {
        "NFL": "New York Giants at New England Patriots",
        "NBA": "Los Angeles Lakers at Boston Celtics",
    },
    "event_result": {"NFL": "Giants 24 - Patriots 17", "NBA": "Lakers 112 - Celtics 105"},
    "event_result_abbrev": {"NFL": "NYG 24 - NE 17", "NBA": "LAL 112 - BOS 105"},
    "exception_keyword": {"NFL": "prime vision", "NBA": "league pass", "NHL": "center ice"},
    "exception_keyword_title": {"NFL": "Prime Vision", "NBA": "League Pass", "NHL": "Center Ice"},
    "final_score": {
        "NBA": "118-105",
        "NFL": "31-17",
        "MLB": "6-3",
        "NHL": "4-2",
        "NCAAM": "82-68",
        "NCAAF": "24-21",
        "Soccer": "2-0",
    },
    "football_passing_leader_name": {"NFL": "Jared Goff", "NCAAF": "Davis Warren"},
    "football_passing_leader_stats": {
        "NFL": "28/35, 312 YDS, 3 TD",
        "NCAAF": "18/29, 187 YDS, 2 TD",
    },
    "football_receiving_leader_name": {"NFL": "Amon-Ra St. Brown", "NCAAF": "Colston Loveland"},
    "football_receiving_leader_stats": {
        "NFL": "9 REC, 118 YDS, 1 TD",
        "NCAAF": "7 REC, 85 YDS, 1 TD",
    },
    "football_rushing_leader_name": {"NFL": "Jahmyr Gibbs", "NCAAF": "Donovan Edwards"},
    "football_rushing_leader_stats": {
        "NFL": "18 CAR, 127 YDS, 1 TD",
        "NCAAF": "22 CAR, 98 YDS, 1 TD",
    },
    "game_date": {
        "NBA": "Monday, November 24, 2025",
        "NFL": "Thursday, November 27, 2025",
        "MLB": "Friday, April 04, 2025",
        "NHL": "Saturday, November 29, 2025",
        "NCAAM": "Tuesday, January 14, 2025",
        "NCAAF": "Saturday, November 29, 2025",
        "Soccer": "Sunday, December 01, 2025",
    },
    "game_date_short": {
        "NBA": "Nov 24",
        "NFL": "Nov 27",
        "MLB": "Apr 04",
        "NHL": "Nov 29",
        "NCAAM": "Jan 14",
        "NCAAF": "Nov 29",
        "Soccer": "Dec 01",
    },
    "game_day": {
        "NBA": "Monday",
        "NFL": "Thursday",
        "MLB": "Friday",
        "NHL": "Saturday",
        "NCAAM": "Tuesday",
        "NCAAF": "Saturday",
        "Soccer": "Sunday",
    },
    "game_day_short": {
        "NBA": "Mon",
        "NFL": "Thu",
        "MLB": "Fri",
        "NHL": "Sat",
        "NCAAM": "Tue",
        "NCAAF": "Sat",
        "Soccer": "Sun",
    },
    "game_time": {
        "NBA": "07:00 PM EST",
        "NFL": "01:00 PM EST",
        "MLB": "12:10 PM EST",
        "NHL": "07:00 PM EST",
        "NCAAM": "07:00 PM EST",
        "NCAAF": "12:00 PM EST",
        "Soccer": "10:30 AM EST",
    },
    "games_back": {
        "NBA": "0.0",
        "NFL": "0.0",
        "MLB": "0.0",
        "NHL": "0.0",
        "NCAAM": "0.0",
        "NCAAF": "0.0",
        "Soccer": "0.0",
    },
    "gracenote_category": {
        "NBA": "NBA Basketball",
        "NFL": "NFL Football",
        "MLB": "MLB Baseball",
        "NHL": "NHL Hockey",
        "NCAAM": "College Basketball",
        "NCAAF": "College Football",
        "Soccer": "Premier League Soccer",
    },
    "head_coach": {
        "NBA": "J.B. Bickerstaff",
        "NFL": "Dan Campbell",
        "MLB": "A.J. Hinch",
        "NHL": "Derek Lalonde",
        "NCAAM": "Dusty May",
        "NCAAF": "Sherrone Moore",
        "Soccer": "Arne Slot",
    },
    "home_away_text": {
        "NBA": "at home",
        "NFL": "at home",
        "MLB": "at home",
        "NHL": "at home",
        "NCAAM": "at home",
        "NCAAF": "at home",
        "Soccer": "at home",
    },
    "home_record": {
        "NBA": "7-1",
        "NFL": "5-0",
        "MLB": "46-35",
        "NHL": "8-4-1",
        "NCAAM": "2-0",
        "NCAAF": "5-1",
        "Soccer": "6-0-1",
    },
    "home_streak": {
        "NBA": "W5",
        "NFL": "W5",
        "MLB": "W2",
        "NHL": "W3",
        "NCAAM": "W2",
        "NCAAF": "W4",
        "Soccer": "W4",
    },
    "home_team": {
        "NBA": "Detroit Pistons",
        "NFL": "Detroit Lions",
        "MLB": "Detroit Tigers",
        "NHL": "Detroit Red Wings",
        "NCAAM": "Michigan Wolverines",
        "NCAAF": "Michigan Wolverines",
        "Soccer": "Liverpool",
    },
    "home_team_abbrev": {
        "NBA": "DET",
        "NFL": "DET",
        "MLB": "DET",
        "NHL": "DET",
        "NCAAM": "MICH",
        "NCAAF": "MICH",
        "Soccer": "LIV",
    },
    "home_team_abbrev_lower": {
        "NBA": "det",
        "NFL": "det",
        "MLB": "det",
        "NHL": "det",
        "NCAAM": "mich",
        "NCAAF": "mich",
        "Soccer": "liv",
    },
    "home_team_college_conference": {"NCAAM": "Big Ten", "NCAAF": "Big Ten"},
    "home_team_college_conference_abbrev": {"NCAAM": "B1G", "NCAAF": "B1G"},
    "home_team_logo": {"All": "https://a.espncdn.com/i/teamlogos/..."},
    "home_team_pascal": {
        "NBA": "DetroitPistons",
        "NFL": "DetroitLions",
        "MLB": "DetroitTigers",
        "NHL": "DetroitRedWings",
        "NCAAM": "MichiganWolverines",
        "NCAAF": "MichiganWolverines",
        "Soccer": "Liverpool",
    },
    "home_team_pro_conference": {
        "NBA": "Eastern Conference",
        "NFL": "National Football Conference",
        "MLB": "American League",
        "NHL": "Eastern Conference",
    },
    "home_team_pro_conference_abbrev": {"NBA": "East", "NFL": "NFC", "MLB": "AL", "NHL": "East"},
    "home_team_pro_division": {
        "NBA": "Central",
        "NFL": "NFC North",
        "MLB": "AL Central",
        "NHL": "Atlantic Division",
        "Soccer": "English Premier League",
    },
    "home_team_rank": {"NCAAM": "#5", "NCAAF": "#12"},
    "home_team_record": {
        "NBA": "14-2",
        "NFL": "10-1",
        "MLB": "87-75",
        "NHL": "13-8-1",
        "NCAAM": "4-0",
        "NCAAF": "9-2",
        "Soccer": "11-1-2",
    },
    "home_team_score": {"NBA": "105", "NFL": "24", "MLB": "5", "NHL": "3"},
    "home_team_seed": {"NBA": "1st", "NFL": "2nd", "MLB": "3rd", "NHL": "4th"},
    "home_team_streak": {
        "NBA": "W5",
        "NFL": "L2",
        "MLB": "W3",
        "NHL": "L1",
        "NCAAM": "W7",
        "NCAAF": "W4",
        "Soccer": "W2",
    },
    "home_win_pct": {
        "NBA": "0.875",
        "NFL": "1.000",
        "MLB": "0.568",
        "NHL": "0.615",
        "NCAAM": "1.000",
        "NCAAF": "0.833",
        "Soccer": "0.857",
    },
    "hours_until": {
        "NBA": "4",
        "NFL": "72",
        "MLB": "3144",
        "NHL": "120",
        "NCAAM": "1224",
        "NCAAF": "120",
        "Soccer": "168",
    },
    "is_away": {
        "NBA": "false",
        "NFL": "false",
        "MLB": "false",
        "NHL": "false",
        "NCAAM": "false",
        "NCAAF": "false",
        "Soccer": "false",
    },
    "is_home": {
        "NBA": "true",
        "NFL": "true",
        "MLB": "true",
        "NHL": "true",
        "NCAAM": "true",
        "NCAAF": "true",
        "Soccer": "true",
    },
    "is_national_broadcast": {
        "NBA": "true",
        "NFL": "true",
        "MLB": "true",
        "NHL": "true",
        "NCAAM": "true",
        "NCAAF": "true",
        "Soccer": "true",
    },
    "is_playoff": {
        "NBA": "false",
        "NFL": "false",
        "MLB": "false",
        "NHL": "false",
        "NCAAM": "false",
        "NCAAF": "false",
        "Soccer": "false",
    },
    "is_preseason": {
        "NBA": "false",
        "NFL": "false",
        "MLB": "false",
        "NHL": "false",
        "NCAAM": "false",
        "NCAAF": "false",
        "Soccer": "false",
    },
    "is_ranked": {"NCAAM": "true", "NCAAF": "true"},
    "is_ranked_matchup": {"NCAAM": "true", "NCAAF": "true"},
    "is_regular_season": {
        "NBA": "true",
        "NFL": "true",
        "MLB": "true",
        "NHL": "true",
        "NCAAM": "true",
        "NCAAF": "true",
        "Soccer": "true",
    },
    "is_rematch": {"NBA": "true", "NFL": "true", "MLB": "true"},
    "last_10_record": {
        "NBA": "10-0",
        "NFL": "9-1",
        "MLB": "7-3",
        "NHL": "6-4",
        "NCAAM": "4-0",
        "NCAAF": "8-2",
        "Soccer": "9-0-1",
    },
    "last_5_record": {
        "NBA": "5-0",
        "NFL": "5-0",
        "MLB": "4-1",
        "NHL": "3-2",
        "NCAAM": "4-0",
        "NCAAF": "5-0",
        "Soccer": "5-0",
    },
    "league": {
        "NBA": "NBA",
        "NFL": "NFL",
        "MLB": "MLB",
        "NHL": "NHL",
        "NCAAM": "NCAAM",
        "NCAAF": "NCAAF",
        "Soccer": "Premier League",
    },
    "league_id": {
        "NBA": "nba",
        "NFL": "nfl",
        "MLB": "mlb",
        "NHL": "nhl",
        "NCAAM": "ncaam",
        "NCAAF": "ncaaf",
        "Soccer": "epl",
    },
    "league_name": {
        "NBA": "NBA",
        "NFL": "NFL",
        "MLB": "MLB",
        "NHL": "NHL",
        "NCAAM": "NCAAM",
        "NCAAF": "NCAAF",
        "Soccer": "Premier League",
    },
    "league_slug": {
        "NBA": "nba",
        "NFL": "nfl",
        "MLB": "mlb",
        "NHL": "nhl",
        "NCAAM": "mens-college-basketball",
        "NCAAF": "college-football",
        "Soccer": "eng.1",
    },
    "loser": {"NFL": "Patriots", "NBA": "Celtics"},
    "loser_abbrev": {"NFL": "NE", "NBA": "BOS"},
    "matchup": {
        "NBA": "Indiana Pacers @ Detroit Pistons",
        "NFL": "Green Bay Packers @ Detroit Lions",
        "MLB": "Cleveland Guardians @ Detroit Tigers",
        "NHL": "New Jersey Devils @ Detroit Red Wings",
        "NCAAM": "Ohio State Buckeyes @ Michigan Wolverines",
        "NCAAF": "Ohio State Buckeyes @ Michigan Wolverines",
        "Soccer": "Manchester City @ Liverpool",
    },
    "matchup_abbrev": {
        "NBA": "IND @ DET",
        "NFL": "GB @ DET",
        "MLB": "CLE @ DET",
        "NHL": "NJD @ DET",
        "NCAAM": "OSU @ MICH",
        "NCAAF": "OSU @ MICH",
        "Soccer": "MCI @ LIV",
    },
    "odds_details": {
        "NBA": "DET -6.5",
        "NFL": "DET -7.5",
        "MLB": "DET -1.5",
        "NHL": "NJD -1.5",
        "NCAAM": "MICH -8.5",
        "NCAAF": "OSU -7.0",
        "Soccer": "LIV -0.5",
    },
    "odds_moneyline": {
        "NBA": "-250",
        "NFL": "-320",
        "MLB": "-135",
        "NHL": "+115",
        "NCAAM": "-350",
        "NCAAF": "+220",
        "Soccer": "-140",
    },
    "odds_opponent_moneyline": {
        "NBA": "+200",
        "NFL": "+260",
        "MLB": "+115",
        "NHL": "-135",
        "NCAAM": "+280",
        "NCAAF": "-275",
        "Soccer": "+380",
    },
    "odds_opponent_spread": {
        "NBA": "-110",
        "NFL": "-110",
        "MLB": "-120",
        "NHL": "-130",
        "NCAAM": "-110",
        "NCAAF": "-110",
        "Soccer": "-120",
    },
    "odds_over_under": {
        "NBA": "221.5",
        "NFL": "47.5",
        "MLB": "8.5",
        "NHL": "6.0",
        "NCAAM": "145.5",
        "NCAAF": "48.5",
        "Soccer": "2.5",
    },
    "odds_provider": {
        "NBA": "ESPN BET",
        "NFL": "ESPN BET",
        "MLB": "ESPN BET",
        "NHL": "ESPN BET",
        "NCAAM": "ESPN BET",
        "NCAAF": "ESPN BET",
        "Soccer": "ESPN BET",
    },
    "odds_spread": {
        "NBA": "6.5",
        "NFL": "7.5",
        "MLB": "1.5",
        "NHL": "1.5",
        "NCAAM": "8.5",
        "NCAAF": "7.0",
        "Soccer": "0.5",
    },
    "opponent": {
        "NBA": "Indiana Pacers",
        "NFL": "Green Bay Packers",
        "MLB": "Cleveland Guardians",
        "NHL": "New Jersey Devils",
        "NCAAM": "Ohio State Buckeyes",
        "NCAAF": "Ohio State Buckeyes",
        "Soccer": "Manchester City",
    },
    "opponent_abbrev": {
        "NBA": "IND",
        "NFL": "GB",
        "MLB": "CLE",
        "NHL": "NJD",
        "NCAAM": "OSU",
        "NCAAF": "OSU",
        "Soccer": "MCI",
    },
    "opponent_abbrev_lower": {
        "NBA": "ind",
        "NFL": "gb",
        "MLB": "cle",
        "NHL": "njd",
        "NCAAM": "osu",
        "NCAAF": "osu",
        "Soccer": "mci",
    },
    "opponent_college_conference": {"NCAAM": "Big Ten", "NCAAF": "Big Ten"},
    "opponent_college_conference_abbrev": {"NCAAM": "B1G", "NCAAF": "B1G"},
    "opponent_is_ranked": {"NCAAM": "true", "NCAAF": "true"},
    "opponent_losses": {
        "NBA": "8",
        "NFL": "4",
        "MLB": "70",
        "NHL": "7",
        "NCAAM": "1",
        "NCAAF": "1",
        "Soccer": "3",
    },
    "opponent_papg": {
        "NBA": "118.1",
        "NFL": "23.5",
        "MLB": "4.2",
        "NHL": "2.8",
        "NCAAM": "68.5",
        "NCAAF": "14.8",
        "Soccer": "1.4",
    },
    "opponent_ppg": {
        "NBA": "115.2",
        "NFL": "26.8",
        "MLB": "5.1",
        "NHL": "3.4",
        "NCAAM": "76.3",
        "NCAAF": "38.2",
        "Soccer": "2.1",
    },
    "opponent_pro_conference": {
        "NBA": "Eastern Conference",
        "NFL": "National Football Conference",
        "MLB": "American League",
        "NHL": "Eastern Conference",
    },
    "opponent_pro_conference_abbrev": {"NBA": "East", "NFL": "NFC", "MLB": "AL", "NHL": "East"},
    "opponent_pro_division": {
        "NBA": "Central",
        "NFL": "NFC North",
        "MLB": "AL Central",
        "NHL": "Metropolitan Division",
        "Soccer": "English Premier League",
    },
    "opponent_rank": {"NCAAM": "#25", "NCAAF": "#2"},
    "opponent_rank_display": {"NCAAM": "#25", "NCAAF": "#2"},
    "opponent_record": {
        "NBA": "8-8",
        "NFL": "7-4",
        "MLB": "92-70",
        "NHL": "15-7-2",
        "NCAAM": "3-1",
        "NCAAF": "10-1",
        "Soccer": "7-4-3",
    },
    "opponent_score": {
        "NBA": "105",
        "NFL": "17",
        "MLB": "3",
        "NHL": "2",
        "NCAAM": "68",
        "NCAAF": "21",
        "Soccer": "0",
    },
    "opponent_ties": {"NFL": "0", "NCAAF": "0", "Soccer": "4"},
    "opponent_win_pct": {
        "NBA": "0.500",
        "NFL": "0.636",
        "MLB": "0.568",
        "NHL": "0.667",
        "NCAAM": "0.750",
        "NCAAF": "0.909",
        "Soccer": "0.500",
    },
    "opponent_wins": {
        "NBA": "8",
        "NFL": "7",
        "MLB": "92",
        "NHL": "15",
        "NCAAM": "3",
        "NCAAF": "10",
        "Soccer": "7",
    },
    "overtime_text": {
        "NBA": "in overtime",
        "NFL": "in overtime",
        "MLB": "in extra innings",
        "NHL": "in overtime",
        "NCAAM": "in overtime",
        "NCAAF": "in overtime",
    },
    "playoff_seed": {"NBA": "1", "NFL": "1", "MLB": "6", "NHL": "4", "NCAAF": "4"},
    "pro_conference": {
        "NBA": "Eastern Conference",
        "NFL": "National Football Conference",
        "MLB": "American League",
        "NHL": "Eastern Conference",
    },
    "pro_conference_abbrev": {"NBA": "East", "NFL": "NFC", "MLB": "AL", "NHL": "East"},
    "pro_division": {
        "NBA": "Central",
        "NFL": "NFC North",
        "MLB": "AL Central",
        "NHL": "Atlantic Division",
        "Soccer": "English Premier League",
    },
    "rematch_city": {
        "NBA": "Indianapolis",
        "NFL": "Green Bay",
        "MLB": "Cleveland",
        "NCAAF": "Columbus",
        "Soccer": "Manchester",
    },
    "rematch_date": {
        "NBA": "October 28, 2025",
        "NFL": "September 14, 2025",
        "MLB": "September 28, 2024",
        "NCAAF": "November 30, 2024",
        "Soccer": "March 10, 2025",
    },
    "rematch_days_since": {"NBA": "27", "NFL": "74", "MLB": "188", "NCAAF": "364", "Soccer": "266"},
    "rematch_result": {"NBA": "win", "NFL": "win", "MLB": "win", "NCAAF": "win", "Soccer": "win"},
    "rematch_score": {
        "NBA": "112-103",
        "NFL": "34-20",
        "MLB": "5-3",
        "NCAAF": "13-10",
        "Soccer": "2-1",
    },
    "rematch_score_abbrev": {
        "NBA": "W 112-103",
        "NFL": "W 34-20",
        "MLB": "W 5-3",
        "NCAAF": "W 13-10",
        "Soccer": "W 2-1",
    },
    "rematch_season_series": {
        "NBA": "1-0",
        "NFL": "1-0",
        "MLB": "10-9",
        "NHL": "0-0",
        "NCAAM": "0-0",
        "NCAAF": "0-0",
        "Soccer": "0-0",
    },
    "rematch_venue": {
        "NBA": "Indianapolis",
        "NFL": "Green Bay",
        "MLB": "Cleveland",
        "NCAAF": "Columbus",
        "Soccer": "Manchester",
    },
    "result": {
        "NBA": "win",
        "NFL": "win",
        "MLB": "win",
        "NHL": "win",
        "NCAAM": "win",
        "NCAAF": "win",
        "Soccer": "win",
    },
    "result_text": {
        "NBA": "defeated",
        "NFL": "defeated",
        "MLB": "defeated",
        "NHL": "defeated",
        "NCAAM": "defeated",
        "NCAAF": "defeated",
        "Soccer": "defeated",
    },
    "result_verb": {
        "NBA": "beat",
        "NFL": "beat",
        "MLB": "beat",
        "NHL": "beat",
        "NCAAM": "beat",
        "NCAAF": "beat",
        "Soccer": "beat",
    },
    "score": {
        "NBA": "118-105",
        "NFL": "31-17",
        "MLB": "6-3",
        "NHL": "4-2",
        "NCAAM": "82-68",
        "NCAAF": "24-21",
        "Soccer": "2-0",
    },
    "score_diff": {
        "NBA": "+13",
        "NFL": "+14",
        "MLB": "+3",
        "NHL": "+2",
        "NCAAM": "+14",
        "NCAAF": "+3",
        "Soccer": "+2",
    },
    "score_differential": {
        "NBA": "13",
        "NFL": "14",
        "MLB": "3",
        "NHL": "2",
        "NCAAM": "14",
        "NCAAF": "3",
        "Soccer": "2",
    },
    "score_differential_text": {
        "NBA": "by 13 points",
        "NFL": "by 14 points",
        "MLB": "by 3 runs",
        "NHL": "by 2 goals",
        "NCAAM": "by 14 points",
        "NCAAF": "by 3 points",
        "Soccer": "by 2 goals",
    },
    "season_series": {
        "NBA": "1-0",
        "NFL": "1-0",
        "MLB": "10-9",
        "NHL": "0-0",
        "NCAAM": "0-0",
        "NCAAF": "0-0",
        "Soccer": "0-0",
    },
    "season_series_leader": {
        "NBA": "Detroit Pistons",
        "NFL": "Detroit Lions",
        "MLB": "Detroit Tigers",
        "NHL": "tied",
        "NCAAM": "tied",
        "NCAAF": "tied",
        "Soccer": "tied",
    },
    "season_series_opponent_wins": {
        "NBA": "0",
        "NFL": "0",
        "MLB": "9",
        "NHL": "0",
        "NCAAM": "0",
        "NCAAF": "0",
        "Soccer": "0",
    },
    "season_series_team_wins": {
        "NBA": "1",
        "NFL": "1",
        "MLB": "10",
        "NHL": "0",
        "NCAAM": "0",
        "NCAAF": "0",
        "Soccer": "0",
    },
    "season_type": {
        "NBA": "regular",
        "NFL": "regular",
        "MLB": "regular",
        "NHL": "regular",
        "NCAAM": "regular",
        "NCAAF": "regular",
        "Soccer": "regular",
    },
    "soccer_match_league": {"Soccer": "UEFA Champions League"},
    "soccer_match_league_id": {"Soccer": "uefa.champions"},
    "soccer_match_league_logo": {"Soccer": "https://a.espncdn.com/i/leaguelogos/soccer/500/2.png"},
    "soccer_primary_league": {"Soccer": "English Premier League"},
    "soccer_primary_league_id": {"Soccer": "eng.1"},
    "sport": {
        "NBA": "Basketball",
        "NFL": "Football",
        "MLB": "Baseball",
        "NHL": "Hockey",
        "NCAAM": "Basketball",
        "NCAAF": "Football",
        "Soccer": "Soccer",
    },
    "sport_lower": {
        "NBA": "basketball",
        "NFL": "football",
        "MLB": "baseball",
        "NHL": "hockey",
        "NCAAM": "basketball",
        "NCAAF": "football",
        "Soccer": "soccer",
    },
    "sport_title": {
        "NBA": "Basketball",
        "NFL": "Football",
        "MLB": "Baseball",
        "NHL": "Hockey",
        "NCAAM": "Basketball",
        "NCAAF": "Football",
        "Soccer": "Soccer",
    },
    "streak": {
        "NBA": "12",
        "NFL": "7",
        "MLB": "3",
        "NHL": "2",
        "NCAAM": "4",
        "NCAAF": "5",
        "Soccer": "4",
    },
    "streak_description": {
        "NBA": "on a 12-game win streak",
        "NFL": "on a 7-game win streak",
        "MLB": "on a 3-game win streak",
        "NHL": "on a 2-game win streak",
    },
    "streak_raw": {
        "NBA": "12",
        "NFL": "7",
        "MLB": "3",
        "NHL": "2",
        "NCAAM": "4",
        "NCAAF": "5",
        "Soccer": "4",
    },
    "streak_type": {"NBA": "win", "NFL": "win", "MLB": "win", "NHL": "loss"},
    "team_abbrev": {
        "NBA": "DET",
        "NFL": "DET",
        "MLB": "DET",
        "NHL": "DET",
        "NCAAM": "MICH",
        "NCAAF": "MICH",
        "Soccer": "LIV",
    },
    "team_abbrev_lower": {
        "NBA": "det",
        "NFL": "det",
        "MLB": "det",
        "NHL": "det",
        "NCAAM": "mich",
        "NCAAF": "mich",
        "Soccer": "liv",
    },
    "team_logo": {"All": "https://a.espncdn.com/i/teamlogos/..."},
    "team_losses": {
        "NBA": "2",
        "NFL": "1",
        "MLB": "75",
        "NHL": "8",
        "NCAAM": "0",
        "NCAAF": "2",
        "Soccer": "2",
    },
    "team_name": {
        "NBA": "Detroit Pistons",
        "NFL": "Detroit Lions",
        "MLB": "Detroit Tigers",
        "NHL": "Detroit Red Wings",
        "NCAAM": "Michigan Wolverines",
        "NCAAF": "Michigan Wolverines",
        "Soccer": "Liverpool",
    },
    "team_name_pascal": {
        "NBA": "DetroitPistons",
        "NFL": "DetroitLions",
        "MLB": "DetroitTigers",
        "NHL": "DetroitRedWings",
        "NCAAM": "MichiganWolverines",
        "NCAAF": "MichiganWolverines",
        "Soccer": "Liverpool",
    },
    "team_papg": {
        "NBA": "112.4",
        "NFL": "18.2",
        "MLB": "4.3",
        "NHL": "3.2",
        "NCAAM": "71.5",
        "NCAAF": "17.9",
        "Soccer": "0.9",
    },
    "team_ppg": {
        "NBA": "119.5",
        "NFL": "31.5",
        "MLB": "4.7",
        "NHL": "3.0",
        "NCAAM": "89.8",
        "NCAAF": "29.3",
        "Soccer": "2.4",
    },
    "team_rank": {"NCAAM": "#1", "NCAAF": "#1"},
    "team_rank_display": {"NCAAM": "#1", "NCAAF": "#1"},
    "team_record": {
        "NBA": "14-2",
        "NFL": "10-1",
        "MLB": "87-75",
        "NHL": "13-8-1",
        "NCAAM": "4-0",
        "NCAAF": "9-2",
        "Soccer": "11-1-2",
    },
    "team_score": {
        "NBA": "118",
        "NFL": "31",
        "MLB": "6",
        "NHL": "4",
        "NCAAM": "82",
        "NCAAF": "24",
        "Soccer": "2",
    },
    "team_ties": {"NFL": "0", "NCAAF": "0", "Soccer": "1"},
    "team_win_pct": {
        "NBA": "0.875",
        "NFL": "0.909",
        "MLB": "0.537",
        "NHL": "0.614",
        "NCAAM": "1.000",
        "NCAAF": "0.818",
        "Soccer": "0.786",
    },
    "team_wins": {
        "NBA": "14",
        "NFL": "10",
        "MLB": "87",
        "NHL": "13",
        "NCAAM": "4",
        "NCAAF": "9",
        "Soccer": "11",
    },
    "today_tonight": {
        "NBA": "tonight",
        "NFL": "today",
        "MLB": "tonight",
        "NHL": "tonight",
        "NCAAM": "tonight",
        "NCAAF": "today",
        "Soccer": "today",
    },
    "today_tonight_title": {
        "NBA": "Tonight",
        "NFL": "Today",
        "MLB": "Tonight",
        "NHL": "Tonight",
        "NCAAM": "Tonight",
        "NCAAF": "Today",
        "Soccer": "Today",
    },
    "venue": {
        "NBA": "Little Caesars Arena",
        "NFL": "Ford Field",
        "MLB": "Comerica Park",
        "NHL": "Little Caesars Arena",
        "NCAAM": "Crisler Center",
        "NCAAF": "Michigan Stadium",
        "Soccer": "Anfield",
    },
    "venue_city": {
        "NBA": "Detroit",
        "NFL": "Detroit",
        "MLB": "Detroit",
        "NHL": "Detroit",
        "NCAAM": "Ann Arbor",
        "NCAAF": "Ann Arbor",
        "Soccer": "Liverpool",
    },
    "venue_full": {
        "NBA": "Little Caesars Arena, Detroit, MI",
        "NFL": "Ford Field, Detroit, MI",
        "MLB": "Comerica Park, Detroit, MI",
        "NHL": "Little Caesars Arena, Detroit, MI",
        "NCAAM": "Crisler Center, Ann Arbor, MI",
        "NCAAF": "Michigan Stadium, Ann Arbor, MI",
        "Soccer": "Anfield, Liverpool, ENG",
    },
    "venue_state": {
        "NBA": "MI",
        "NFL": "MI",
        "MLB": "MI",
        "NHL": "MI",
        "NCAAM": "MI",
        "NCAAF": "MI",
        "Soccer": "ENG",
    },
    "vs_@": {
        "NBA": "vs",
        "NFL": "vs",
        "MLB": "vs",
        "NHL": "vs",
        "NCAAM": "vs",
        "NCAAF": "vs",
        "Soccer": "vs",
    },
    "vs_at": {
        "NBA": "vs",
        "NFL": "vs",
        "MLB": "vs",
        "NHL": "vs",
        "NCAAM": "vs",
        "NCAAF": "vs",
        "Soccer": "vs",
    },
    "winner": {"NFL": "Giants", "NBA": "Lakers"},
    "winner_abbrev": {"NFL": "NYG", "NBA": "LAL"},
}
